### PR TITLE
Add an option to set the post_limit

### PR DESCRIPTION
**Pull request by jbennett**
This addresses issue #11

### CODE REVIEW

**Comment by jaredcwhite** [comment]
Thanks @jbennett!

**Comment by jbennett** [comment]
Happy to contribute. Thanks for doing most of the heavy lifting!

**Comment by jaredcwhite** [comment]
@jbennett Hey I hate to bother you after the fact, but I think maybe there's a second assign post_limit in there? Shouldn't there just be one assignment line?

**Comment by jbennett** [comment]
🤦🏻‍♂️

Yup. PR incoming

**Pull request merged**
